### ISSUE TITLE
Think about some backup strategy of maildir with docker-mailserver

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#110]
contained in docker volume inspect docker-mailserver

**Comment by bjoernkessler** [comment]
Backup is done via a cron job on secure. Daily Backups are saved via remote login on Quad as user backuper on drive x.

**Comment by bjoernkessler** [comment]
Design of a bash-script that is controlling the backups. 

- All Backupps younger than two weeks should be kept. 
- Backups older then two weeks should be kept only for Wednesdays and Sundays, but at least two files per week. 
- For Backups that are older than one mounth only one file per week should be kept, if present, this will be the sunday dump, if not the saturday, friday ...
- If any of the expected files are missing, log it to an error-file

**Comment by bjoernkessler** [comment]
The script lives in /home/backuper/bin on Quad. It is run by cron every monday at 4 a.m. Log is going to /home/backuper/log.
Improvements are:
- [ ] use ctime instead of the filename to get the age of the files
- [ ] keep one file per week, if sunday exists take sunday, else move ot saturday, else to friday ...

**Comment by HirschSt** [comment]
maildir is very dead
