### ISSUE TITLE
Check sources for unusual whitespace

### ISSUE THREAD

**Issue by HirschSt** [rism-international/tasks#959]
for reference see https://en.wikipedia.org/wiki/Whitespace_character

with regexp

**Comment by HirschSt** [comment]
done with https://github.com/rism-international/muscat-maintenance/commit/9fe7a5891801313c6d2d041cb4ca3a2e62e9a68b

please check https://github.com/rism-international/muscat-maintenance/blob/master/report/2022-05-03_ws.csv

**Comment by BaMikusi** [comment]
I skimmed the spreadsheet and it seems to me that the unusual whitespaces caught therein could be turned into regular whitespaces. But, depending on the context, some refinement would be useful:
- if the whitespace appears at the very beginning or the very end of a field (or the field may in fact contain nothing but a whitespace) it should better be simply omitted
- if there are already other whitespaces directly next to the irregular whitespace, it should also be simply deleted (having two or three whitespaces instead of a single one could mislead the search just as well as an incorrectly encoded one)
(At least it seems to me so -- but feel free to remind me of aspects I may have forgotten about.)

Another point: several of these source records in fact contain unusual whitespaces because there is one in an authority record which is referenced in them -- e.g. there is a [HAIRSPACE] at the very end of three Körperschaften {Sammlung Lischka, Rainer (*1942) ; Nachlass Georg (Preussen, Prinz) ; and Nachlass Hombsch, Hans (1935-2009) }, which results in a superfluous [HAIRSPACE] in about a thousand source records. (NB: I have not corrected these authorities so as not to mess up the up-to-date status of the spreadsheet, but the authority files could in fact also be the subject of such a search for unusual whitespaces in order to prevent such errors from creeping in again after a correction by script.)

**Comment by HirschSt** [comment]
Probably changing all occurences to the normal whitespace would be the best solution (except starting and ending of course). 

Concerning authority: with linked fields (e.g. 710, wg. https://muscat.rism.info/admin/sources/450065547) this can be only solved by correcting the autority record itself, with unlinked textfields (as with 852$z, eg. https://muscat.rism.info/admin/sources/1001178337) this problem is resolved by changing the source record. We have both cases.

At the moment it  is sufficient to get an impression how many irregular whitespaces we have, now I would create a new ticket for the maintenance

BTW: the authority and other db fields are checked as well and are also included in the spreadsheet.

**Comment by BaMikusi** [comment]
Many thanks for the explanations. Indeed, I failed to pay close attention that only some part of the Provenances were actually Institution authorities -- in fact the only one was "Nachlass Georg (Preussen, Prinz) ", which I have now amended (and the change has indeed been immediately saved into all the related source records as well).

**Comment by HirschSt** [comment]
Perfect, thanks

**Comment by HirschSt** [comment]
Perfect, thanks!
